services:
  db:
    container_name: couch_db
    image: 'postgres:14.1-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=couch_db
    ports:
      - "5437:5432"